stages:
  preprocess:
    cmd: .\venv\Scripts\python src/preprocess.py --input data/winequality.csv --output data/processed.csv
    deps:
    - data/winequality.csv
    - src/preprocess.py
    outs:
    - data/processed.csv
  train:
    cmd: .\venv\Scripts\python src/train.py
    deps:
    - data/processed.csv
    - src/train.py
    params:
    - train.max_depth
    - train.n_estimators
    - train.random_state
    - train.test_size
    outs:
    - data/test.csv
    - models/model.pkl
  evaluate:
    cmd: .\venv\Scripts\python src/evaluate.py
    deps:
    - data/test.csv
    - models/model.pkl
    - src/evaluate.py
    metrics:
    - metrics.json:
        cache: false
